repositories:
  - name: cilium
    url: https://helm.cilium.io/

helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 600
  createNamespace: false
  atomic: true

releases:
  - name: cilium
    namespace: kube-system
    chart: cilium/cilium
    version: 1.19.6
    values:
      - values/cilium.yml

  - name: registry
    namespace: registry
    chart: ./charts/registry
    values:
      - values/registry-{{ requiredEnv "ENVIRONMENT" }}.yml

  - name: cilium-lb
    namespace: kube-system
    chart: ./charts/cilium-lb
    needs:
      - kube-system/cilium
