[tools]
helm = "latest"
helmfile = "latest"

[env]
_.file = ".env"

[tasks."render"]
run = '''ENVIRONMENT="$usage_env" helmfile template'''
usage = '''
arg "<env>"
'''

[tasks."apply"]
run = '''ENVIRONMENT="$usage_env" helmfile sync'''
usage = '''
arg "<env>"
'''
