apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default
spec:
  interfaces:
{{- range .Values.l2Announcement.interfaces }}
    - {{ . | quote }}
{{- end }}
  loadBalancerIPs: true
