apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: cluster-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
  {{- if .Values.hostNetwork.enabled }}
  strategy:
    type: Recreate
    rollingUpdate: null
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
    spec:
      {{- if .Values.hostNetwork.enabled }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - name: registry
              containerPort: 5000
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
          readinessProbe:
            httpGet:
              path: /v2/
              port: registry
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v2/
              port: registry
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: registry-storage
